import type { EntityData } from '@/types'

export const ALL_ENTITIES: EntityData[] = [
  {
    id: 'grass',
    name: 'Grass',
    defaultVariant: 'base/grass/grass.png',
    category: 'base',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: null,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'house',
    name: 'House',
    defaultVariant: 'House_Type1.png',
    defaultColor: 'yellow',
    category: 'buildings',
    subcategory: 'houses',
    layer: 'object',
    size: [1, 1],
    availableColors: ['blue', 'green', 'pink', 'red', 'yellow'],
    variants: ['House_Type1.png', 'House_Type2.png', 'House_Type3.png', 'House_Type4.png', 'House_Type5.png'],
    cost: 100,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'market',
    name: 'Market',
    defaultVariant: 'buildings/stores/grocery/market.png',
    category: 'buildings',
    subcategory: 'shopping',
    layer: 'object',
    size: [2, 2],
    cost: 200,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bank',
    name: 'Bank',
    defaultVariant: 'buildings/stores/bank.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [2, 1],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'dentist',
    name: 'Dentist',
    defaultVariant: 'buildings/stores/dentist.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [1, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'apartment-1-1',
    name: 'Apartment',
    defaultVariant: '1-1/Level2.png',
    defaultColor: 'red',
    category: 'buildings',
    subcategory: 'apartments',
    layer: 'object',
    size: [1, 1],
    availableColors: ['blue', 'green', 'pink', 'red', 'yellow'],
    variants: ['1-1/Level1.png', '1-1/Level2.png', '1-1/Level3.png'],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'apartment-1-2',
    name: 'Apartment',
    defaultVariant: '1-2/Level2.png',
    defaultColor: 'red',
    category: 'buildings',
    subcategory: 'apartments',
    layer: 'object',
    size: [1, 2],
    availableColors: ['blue', 'green', 'pink', 'red', 'yellow'],
    variants: ['1-2/Level1.png', '1-2/Level2.png', '1-2/Level3.png'],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'apartment-2-2',
    name: 'Apartment',
    defaultVariant: '2-2/Level2.png',
    defaultColor: 'red',
    category: 'buildings',
    subcategory: 'apartments',
    layer: 'object',
    size: [2, 2],
    availableColors: ['blue', 'green', 'pink', 'red', 'yellow'],
    variants: ['2-2/Level1.png', '2-2/Level2.png', '2-2/Level3.png'],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'hospital',
    name: 'Hospital',
    defaultVariant: 'buildings/emergency/hospital.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'mall',
    name: 'Mall',
    defaultVariant: 'buildings/stores/mall.png',
    category: 'buildings',
    subcategory: 'shopping',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'grocery-store',
    name: 'Grocery Store',
    defaultVariant: 'buildings/stores/grocery/grocery_store.png',
    category: 'buildings',
    subcategory: 'shopping',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'police-station',
    name: 'Police Station',
    defaultVariant: 'buildings/emergency/police_station.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'fire-station',
    name: 'Fire Station',
    defaultVariant: 'buildings/emergency/fire_station.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bar',
    name: 'Bar',
    defaultVariant: 'buildings/restaurants/restaurant_bar.png',
    category: 'buildings',
    subcategory: 'restaurants',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'cafe',
    name: 'Cafe',
    defaultVariant: 'buildings/restaurants/restaurant_cafe.png',
    category: 'buildings',
    subcategory: 'restaurants',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'burger-joint',
    name: 'Burger Joint',
    defaultVariant: 'buildings/restaurants/restaurant_burger.png',
    subcategory: 'restaurants',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'breakfast-spot',
    name: 'Breakfast Spot',
    defaultVariant: 'buildings/restaurants/restaurant_breakfast.png',
    subcategory: 'restaurants',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'sushi-shop',
    name: 'Sushi Shop',
    defaultVariant: 'buildings/restaurants/restaurant_sushi.png',
    subcategory: 'restaurants',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'park-pond',
    name: 'Park Pond',
    defaultVariant: 'decorations/park_pond.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [2, 2],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'park-fountain',
    name: 'Park Fountain',
    defaultVariant: 'decorations/park_fountain.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [2, 2],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'gas-station',
    name: 'Gas Station',
    defaultVariant: 'buildings/stores/gas_station.png',
    category: 'buildings',
    subcategory: 'public',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bus-stop',
    name: 'Bus Stop',
    defaultVariant: 'decorations/bus_stop.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'driveway',
    name: 'Driveway',
    defaultVariant: 'decorations/driveway.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'pool',
    name: 'Pool',
    defaultVariant: 'decorations/pool.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    defaultVariant: 'decorations/landscaping.png',
    category: 'decorations',
    subcategory: null,
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  // Roads
  {
    id: 'road-straight',
    name: 'Road Straight',
    defaultVariant: 'roads/road_straight.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-1',
    name: 'Road Intersection',
    defaultVariant: 'roads/road_intersection_1.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-2',
    name: 'Road Intersection',
    defaultVariant: 'roads/road_intersection_2.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-3',
    name: 'Road Intersection',
    defaultVariant: 'roads/road_intersection_3.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-1',
    name: 'Road Turn',
    defaultVariant: 'roads/road_turn_1.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-2',
    name: 'Road Turn',
    defaultVariant: 'roads/road_turn_2.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-3',
    name: 'Road Turn',
    defaultVariant: 'roads/road_turn_3.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-cap-1',
    name: 'Road Cap',
    defaultVariant: 'roads/road_cap_1.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-cap-2',
    name: 'Road Cap',
    defaultVariant: 'roads/road_cap_2.png',
    category: 'roads',
    subcategory: null,
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
]
