import type { EntityData } from '@/types'

export const ALL_ENTITIES: EntityData[] = [
  {
    id: 'grass-1',
    name: 'Grass',
    texture: 'base/grass/grass.png',
    category: 'base',
    layer: 'base',
    size: [1, 1],
    cost: null,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'house-1',
    name: 'House',
    texture: 'buildings/houses/house_1.png',
    category: 'buildings',
    layer: 'object',
    size: [1, 1],
    cost: 100,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'market-1',
    name: 'Market',
    texture: 'buildings/stores/grocery/market.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 200,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bank-1',
    name: 'Bank',
    texture: 'buildings/stores/bank.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'dentist-1',
    name: 'Dentist',
    texture: 'buildings/stores/dentist.png',
    category: 'buildings',
    layer: 'object',
    size: [1, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'apartment-1',
    name: 'Apartment',
    texture: 'buildings/apartments/apartment_1.png',
    category: 'buildings',
    layer: 'object',
    size: [1, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'apartment-2',
    name: 'Apartment',
    texture: 'buildings/apartments/apartment_green_1x1_level3.png',
    category: 'buildings',
    layer: 'object',
    size: [1, 1],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'hospital-1',
    name: 'Hospital',
    texture: 'buildings/emergency/hospital.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'mall-1',
    name: 'Mall',
    texture: 'buildings/stores/mall.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'grocery-store-1',
    name: 'Grocery Store',
    texture: 'buildings/stores/grocery/grocery_store.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'police-station-1',
    name: 'Police Station',
    texture: 'buildings/emergency/police_station.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'fire-station-1',
    name: 'Fire Station',
    texture: 'buildings/emergency/fire_station.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 2],
    cost: 500,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bar-1',
    name: 'Bar',
    texture: 'buildings/restaurants/restaurant_bar.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'cafe-1',
    name: 'Cafe',
    texture: 'buildings/restaurants/restaurant_cafe.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'burger-joint-1',
    name: 'Burger Joint',
    texture: 'buildings/restaurants/restaurant_burger.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'breakfast-spot-1',
    name: 'Breakfast Spot',
    texture: 'buildings/restaurants/restaurant_breakfast.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'sushi-shop-1',
    name: 'Sushi Shop',
    texture: 'buildings/restaurants/restaurant_sushi.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'park-pond-1',
    name: 'Park Pond',
    texture: 'decorations/park_pond.png',
    category: 'decorations',
    layer: 'object',
    size: [2, 2],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'park-fountain-1',
    name: 'Park Fountain',
    texture: 'decorations/park_fountain.png',
    category: 'decorations',
    layer: 'object',
    size: [2, 2],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'gas-station-1',
    name: 'Gas Station',
    texture: 'buildings/stores/gas_station.png',
    category: 'buildings',
    layer: 'object',
    size: [2, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'bus-stop-1',
    name: 'Bus Stop',
    texture: 'decorations/bus_stop.png',
    category: 'decorations',
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'driveway-1',
    name: 'Driveway',
    texture: 'decorations/driveway.png',
    category: 'decorations',
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'pool-1',
    name: 'Pool',
    texture: 'decorations/pool.png',
    category: 'decorations',
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'landscaping-1',
    name: 'Landscaping',
    texture: 'decorations/landscaping.png',
    category: 'decorations',
    layer: 'object',
    size: [1, 1],
    cost: 300,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  // Roads
  {
    id: 'road-straight',
    name: 'Road Straight',
    texture: 'roads/road_straight.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-1',
    name: 'Road Intersection',
    texture: 'roads/road_intersection_1.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-2',
    name: 'Road Intersection',
    texture: 'roads/road_intersection_2.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-intersection-3',
    name: 'Road Intersection',
    texture: 'roads/road_intersection_3.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-1',
    name: 'Road Turn',
    texture: 'roads/road_turn_1.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-2',
    name: 'Road Turn',
    texture: 'roads/road_turn_2.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-turn-3',
    name: 'Road Turn',
    texture: 'roads/road_turn_3.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-cap-1',
    name: 'Road Cap',
    texture: 'roads/road_cap_1.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
  {
    id: 'road-cap-2',
    name: 'Road Cap',
    texture: 'roads/road_cap_2.png',
    category: 'roads',
    layer: 'base',
    size: [1, 1],
    cost: 5,
    requiredLevel: 1,
    buildTime: 0,
    collectionTime: null,
    currencyValue: null,
    xpValue: null,
  },
]
